import streamlit as st

# Set page config
st.set_page_config(page_title="Lyle Cantalejo Contact Card", page_icon="📇", layout="centered")

# Main container
with st.container():
    st.image("Lyle Photo.jpg", width=250)  # make sure to upload your photo with this exact filename

    st.markdown(
        """
        <h1 style='text-align: center;'>Lyle Cantalejo</h1>
        <h3 style='text-align: center; color: gray;'>Technical Service Manager</h3>
        """,
        unsafe_allow_html=True
    )

    st.markdown("---")

    st.subheader("📍 Company Information")
    st.write("""
    **WEVO Chemical (Asia-Pacific) Pte. Ltd.**  
    German Centre, Office #04-13/14  
    25 International Business Park  
    Singapore, 609916
    """)

    st.subheader("📧 Email Addresses")
    st.write("""
    - Lyle.Cantalejo@wevochemical.com  
    - Lyle.Cantalejo@gmail.com
    """)

    st.subheader("📞 Phone Numbers")
    st.write("""
    - Singapore: +65 699 095 94  
    - Philippines: +63 945 170 2105
    """)

    st.subheader("🚨 In Case of Emergency")
    st.write("""
    **Geejay T. Cantalejo**  
    - Phone: +63 906 236 9758  
    - Address: Lot 8, Block 23, Phase 4A, San Antonio Heights, Santo Tomas, Batangas 4234
    """)

    st.markdown("---")
    st.caption("Generated by Streamlit • Contact Card")

